#pragma once
#include "export.hpp"

namespace day_constructor {
struct ConstructorOptions {
    Options routing;
    RepairOptions repair;
    int iterations = 5000;
    double seconds = 45;
    bool split_resource_tasks = true, use_all_workers = true;
    ConstructorOptions() {
        routing.fixed_cost = 0; routing.seed = 1;
        routing.include_all_tasks = routing.worker_profile_fleet = routing.separate_delivery_routes = true;
        repair.seconds = 30;
    }
};
struct RouteSummary {
    Count duration, distance, start, end;
    std::string vehicle;
};
struct ConstructorResult {
    std::optional<RouteProposal> proposal;
    std::vector<RouteSummary> route_stats;
    std::vector<Key> resource_pairs;
    std::map<int, int> late_inputs, late_seeds;
    std::optional<Count> cost;
    int iterations = 0;
    double seconds = 0;
};

inline ConstructorResult construct(const ds::DayProblem& problem, ConstructorOptions options) {
    require(options.iterations >= 0 && std::isfinite(options.seconds) && options.seconds >= 0, "invalid constructor budget");
    require(!options.routing.route_segments, "coalescing and route segments are alternatives");
    const auto started = std::chrono::steady_clock::now();
    auto elapsed = [&] { return std::chrono::duration<double>(std::chrono::steady_clock::now() - started).count(); };
    const RoutingData routing(problem, options.routing);
    const auto data = routing.data();
    Search search(data, options.routing.seed);
    SearchOptions search_options;
    search_options.iterations = options.iterations > 0 ? options.iterations : std::numeric_limits<int>::max() - 1;
    // Iteration and time limits both apply. Include setup and the initial
    // local search in the budget; a search iteration is not interruptible.
    const auto stop = [&] { return elapsed() >= options.seconds; };
    const auto solution = search.run(search_options, {}, stop);
    ConstructorResult result;
    result.iterations = search.iterations_run;
    if (!solution->isFeasible()) { result.seconds = elapsed(); return result; }
    const vrp::CostEvaluator evaluator(std::vector<double>(data.numLoadDimensions(), 0), 0, 0);
    result.cost = Count(evaluator.cost(*solution));
    for (const auto& route : solution->routes()) result.route_stats.push_back({
        Count(route.duration()), Count(route.distance()), Count(route.startTime()), Count(route.endTime()), data.vehicleType(route.vehicleType()).name});
    result.resource_pairs = routing.resource_pairs;
    result.late_inputs = routing.late_inputs; result.late_seeds = routing.late_seeds;
    const Bundles bundles(routing, *solution, options.split_resource_tasks);
    options.repair.target_routes = options.use_all_workers ? problem.worker_count : 0;
    options.repair.separate_output_routes = options.routing.separate_delivery_routes;
    result.proposal = repair_and_export(bundles, options.repair, [&] { return std::max(0.0, options.seconds - elapsed()); });
    result.seconds = elapsed();
    return result;
}

// Internal proposals are generated by construct()/our semantic repair. This
// overload is not an original-route input to the public scheduling interface.
inline ConstructorResult repair_generated(const ds::DayProblem& problem, ConstructorOptions options,
                                          const std::vector<ProposalTask>& proposal) {
    require(!options.routing.route_segments, "coalescing and route segments are alternatives");
    const auto started = std::chrono::steady_clock::now();
    const RoutingData routing(problem, options.routing);
    std::map<Key, int> indices;
    for (const auto& task : proposal) {
        require(task.worker >= 0 && task.type >= 0, "negative generated route label");
        indices[{task.type, task.worker}] = 0;
    }
    int index = 0;
    for (auto& [key, value] : indices) value = index++;
    require(int(indices.size()) <= problem.worker_count, "too many generated worker routes");
    std::vector<TaskAssignment> assignments;
    for (const auto& task : proposal) assignments.push_back({task.task, indices.at({task.type, task.worker}), task.rank});
    const Bundles bundles(routing, std::move(assignments), options.split_resource_tasks);
    RepairContext context(bundles, true);
    options.repair.target_routes = options.use_all_workers ? problem.worker_count : 0;
    options.repair.separate_output_routes = options.routing.separate_delivery_routes;
    RouteProposal repaired;
    repaired.repaired = Repair(context, options.repair).run(context.initial);
    export_workers(context, repaired);
    ConstructorResult result;
    result.proposal = std::move(repaired);
    result.resource_pairs = routing.resource_pairs;
    result.late_inputs = routing.late_inputs; result.late_seeds = routing.late_seeds;
    result.seconds = std::chrono::duration<double>(std::chrono::steady_clock::now() - started).count();
    return result;
}
}  // namespace day_constructor
