#pragma once
#include "repair.hpp"

namespace day_constructor {
struct ProposalTask { int task, worker, rank, type; };
struct RouteProposal {
    std::vector<ProposalTask> assignments;
    std::vector<std::vector<int>> type_workers;
    RepairResult repaired;
    std::optional<RepairResult> coarse;
    std::vector<std::array<Count, 5>> initial_seed_deficits;
    std::optional<double> seed_seconds;
};

inline std::vector<int> complete_assignment(std::vector<int> assignment, int workers) {
    require(int(assignment.size()) <= workers, "too many routes for worker assignment");
    std::set<int> used;
    for (int worker : assignment) if (worker >= 0)
        require(worker < workers && used.insert(worker).second, "route matching must use distinct valid workers");
    int available = 0;
    for (int& worker : assignment) if (worker < 0) {
        while (used.contains(available)) ++available;
        require(available < workers, "worker assignment exhausted");
        worker = available++;
    }
    return assignment;
}

inline std::vector<std::array<Count, 5>> proposal_seed_deficits(const RepairContext& context, const BundlePlan& plan) {
    const auto& bundles = context.bundles;
    const auto& tasks = bundles.routing.task_data.tasks;
    std::map<int, std::array<Count, hours>> counts;
    for (int crop : context.crop_order) counts[crop].fill(0);
    for (const auto& route : plan) {
        std::vector<int> ids;
        for (int bundle : route) ids.insert(ids.end(), context.members[bundle].begin(), context.members[bundle].end());
        int latest = hours - 1, successor = -1;
        for (auto it = ids.rbegin(); it != ids.rend(); ++it) {
            const auto& task = tasks[*it];
            if (successor >= 0) latest -= 1 + distance(task.point, tasks[successor].point);
            latest = std::min(latest, bundles.late[*it]);
            if (counts.contains(task.crop)) ++counts[task.crop][std::clamp(latest, 0, hours - 1)];
            successor = *it;
        }
    }
    std::vector<std::array<Count, 5>> result;
    for (int crop : context.crop_order) {
        Count required = 0;
        for (int hour = 0; hour < hours; ++hour) {
            required += counts[crop][hour];
            const Count available = bundles.seed_supply.at(crop)[hour];
            if (required > available) result.push_back({crop, hour, required, available, required - available});
        }
    }
    return result;
}

inline void export_workers(const RepairContext& context, RouteProposal& result) {
    const auto& bundles = context.bundles;
    require(result.assignments.empty() && result.type_workers.empty(), "proposal already exported");
    const auto assignment = complete_assignment(result.repaired.workers, bundles.workers.size());
    std::vector<int> worker_type(bundles.workers.size(), 0);
    if (bundles.routing.options.worker_profile_fleet) {
        std::vector<std::pair<Point, int>> profiles;
        for (int worker = 0; worker < int(bundles.workers.size()); ++worker) {
            const auto& value = bundles.workers[worker];
            const auto profile = std::pair(value.start, value.release);
            const auto found = std::find(profiles.begin(), profiles.end(), profile);
            const int type = found - profiles.begin();
            if (found == profiles.end()) { profiles.push_back(profile); result.type_workers.emplace_back(); }
            worker_type[worker] = type;
            result.type_workers[type].push_back(worker);
        }
    } else {
        result.type_workers.emplace_back(bundles.workers.size());
        std::iota(result.type_workers.back().begin(), result.type_workers.back().end(), 0);
    }
    for (size_t route = 0; route < result.repaired.routes.size(); ++route) {
        const int worker = assignment[route];
        int rank = 0;
        for (int bundle : result.repaired.routes[route]) for (int task : context.members[bundle])
            result.assignments.push_back({task, worker, rank++, worker_type[worker]});
    }
    std::stable_sort(result.assignments.begin(), result.assignments.end(), [](auto a, auto b) { return a.worker < b.worker; });
    const int count = bundles.routing.task_data.tasks.size();
    std::vector<bool> seen(count);
    for (const auto& value : result.assignments) {
        require(value.task >= 0 && value.task < count && !seen[value.task], "invalid exported task partition");
        seen[value.task] = true;
    }
    require(std::ranges::all_of(seen, [](bool value) { return value; }), "incomplete exported task partition");
}

// Cold constructor only: the caller supplies its remaining total time, after
// routing. Both phases consume typed proposals generated by our own solver.
inline RouteProposal repair_and_export(const Bundles& bundles, RepairOptions options,
                                      const std::function<double()>& remaining_seconds) {
    RepairContext coarse_context(bundles, false);
    RouteProposal result;
    result.repaired = Repair(coarse_context, options).run(coarse_context.initial);
    if (!bundles.seed_supply.empty()) {
        RepairContext seed_context(bundles, true);
        result.initial_seed_deficits = proposal_seed_deficits(seed_context, result.repaired.routes);
        if (!result.initial_seed_deficits.empty()) {
            result.coarse = std::move(result.repaired);
            const auto assignment = complete_assignment(result.coarse->workers, bundles.workers.size());
            std::vector<std::pair<int, BundleRoute>> ordered;
            for (size_t route = 0; route < assignment.size(); ++route)
                ordered.emplace_back(assignment[route], seed_context.ordered(result.coarse->routes[route]));
            std::sort(ordered.begin(), ordered.end());
            BundlePlan routes;
            for (auto& [worker, route] : ordered) routes.push_back(std::move(route));
            const double remaining = std::max(0.0, remaining_seconds());
            options.seconds = options.seconds > 0 ? std::min(options.seconds, remaining) : remaining;
            result.seed_seconds = options.seconds;
            if (options.seconds == 0) options.iterations = 0;
            result.repaired = Repair(seed_context, options).run(std::move(routes));
        }
    }
    export_workers(coarse_context, result);
    return result;
}
}  // namespace day_constructor
