"""Hour-by-hour opponent sales forecasts, made at dawn, scored on cumulative units sold by each hour
(what decides races): CWAPE = sum_h |S_true(h) - S_pred(h)| / sum_h S_true(h) over hours 0-23.
Forecasts: trailing (our current: mean hourly sales of the last 3 days), blend (daily total from
visible supply; trailing hourly shape, else uniform 6-12), prior (blend total, hourly shape learned
on half of the top-team games per product x day bucket x has-history), mix (0.5 trailing shape +
0.5 prior shape when there is history). Evaluated on the other half of top teams, Kaggle and
Local-LB opponents. Days 3-28."""
import numpy as np, pandas as pd
P = ['wheat', 'carrot', 'tomato', 'strawberry', 'melon', 'egg', 'milk', 'wool', 'fertilizer']
H = [f'h{h}' for h in range(24)]
d = pd.read_csv('hourly/h.csv')
d['rank'] = d.label.str.extract(r'\|(\d+)$')[0].astype(float)
d['src'] = np.select([d.label.str.startswith('ours'), d['rank'] <= 10, d['rank'] > 10, d.label.str.startswith('opp:')],
                     ['ours', 'top10', 'rank11+', 'opp'], 'other')
d['src'] = np.where(d.trace.str.contains('kaggle_ours') & (d.src == 'opp'), 'kaggle_opp', d.src)
d = d[d['product'].isin([1, 2, 3, 4, 5, 6, 7])].sort_values(['trace', 'seat', 'product', 'day']).reset_index(drop=True)
S = d[H].to_numpy(float)
tot = S.sum(1)
g = d.groupby(['trace', 'seat', 'product'])
# trailing 3-day hourly mean (strictly previous days)
trail = np.zeros_like(S)
for k in (1, 2, 3):
    sh = g[H].shift(k).fillna(0).to_numpy(float)
    trail += sh / 3
ttot = trail.sum(1)
vis = d.visible.to_numpy(float)
daily = np.where(d['product'] == 4, vis, 0.5 * ttot + 0.5 * vis)
uni = np.zeros(24); uni[6:13] = 1 / 7
tshape = np.where(ttot[:, None] > 0, trail / np.maximum(ttot, 1e-9)[:, None], uni)
d['bucket'] = pd.cut(d.day, [-1, 9, 14, 22, 29], labels=['d0-9', 'd10-14', 'd15-22', 'd23-29']).astype(str)
d['has_hist'] = ttot > 0
train = (d.src.isin(['top10', 'rank11+'])) & (d.trace.str.extract(r'(\d+)\.txt$')[0].astype(float) % 2 == 0)
key = d['product'].astype(str) + '|' + d.bucket + '|' + d.has_hist.astype(str)
prior = {}
for k, idx in d[train & (tot > 0)].groupby(key[train & (tot > 0)]).groups.items():
    x = S[idx]; prior[k] = x.sum(0) / x.sum()
pshape = np.array([prior.get(k, uni) for k in key])
mshape = np.where(d.has_hist.to_numpy()[:, None], 0.5 * tshape + 0.5 * pshape, pshape)
fc = {'trailing': trail, 'blend': daily[:, None] * tshape, 'prior': daily[:, None] * pshape, 'mix': daily[:, None] * mshape}
C = np.cumsum(S, 1)
test = ~train & d.day.between(3, 28).to_numpy()
rows = []
for name, F in fc.items():
    err = np.abs(np.cumsum(F, 1) - C).sum(1)
    for src in ['top10', 'rank11+', 'kaggle_opp', 'opp']:
        for p in [3, 4, 6, 7, 5]:
            m = test & (d.src == src).to_numpy() & (d['product'] == p).to_numpy()
            if m.sum() < 30: continue
            rows.append((name, src, P[p], err[m].sum() / C[m].sum()))
r = pd.DataFrame(rows, columns=['forecast', 'src', 'product', 'cwape'])
pd.set_option('display.width', 250)
print(r.pivot_table(index=['src', 'product'], columns='forecast', values='cwape').round(2).to_string())
# melon first-wave hour prior (top teams): hour share on the first day with melon sales
m = d[(d['product'] == 4) & train & (tot > 0)]
first = m.groupby(['trace', 'seat']).day.transform('min') == m.day
x = S[m[first].index]
print('top-team first melon day: share of units sold by hour', np.round(np.cumsum(x.sum(0)) / x.sum(), 2)[[3, 6, 8, 9, 10, 12, 16, 20, 23]])
# Export the learned hourly shape prior (train half) as a C++ table: [product][bucket][has_history][hour].
buckets = ['d0-9', 'd10-14', 'd15-22', 'd23-29']
lines = ['// Generated by work/sep25_bc_weakness/q56.py: hourly share of a strong player\'s daily sales,',
         '// by product, day bucket (0-9, 10-14, 15-22, 23-29) and whether it sold the product in the last 3 days.',
         '#pragma once', 'namespace dc10 {', 'inline constexpr float OPP_PRIOR[9][4][2][24] = {']
for p in range(9):
    lines.append('  {')
    for b in buckets:
        cells = []
        for hist in (False, True):
            sh = prior.get(f'{p}|{b}|{hist}', uni)
            cells.append('{' + ', '.join(f'{v:.4f}f' for v in sh) + '}')
        lines.append('    {' + ', '.join(cells) + '},')
    lines.append('  },')
lines += ['};', '}']
open('exp_patch/source/opp_prior.hpp', 'w').write('\n'.join(lines) + '\n')
print('wrote exp_patch/source/opp_prior.hpp')
