name: kaggriculture
channels:
  - conda-forge
dependencies:
  - python=3.12.14
  - pip
  - cmake
  - pip:
      - kaggle-environments==1.32.7
      - numpy==2.5.2
      - pandas==3.0.5
      - scipy==1.18.1
      - requests==2.34.2
      - kaggle==2.2.4
